### ISSUE TITLE
No termination in 3 hours (when I cancelled)?

### ISSUE THREAD

**Issue by metaleap** [E-Sh4rk/Prototype#1]
Hi, after I followed the setup instructions, I successfully `make run` which used the standard `test.ml` which took 4.7s. So far so good! Then I had the funky idea of appending to that file the following def, knowing it'd be a challenge without any type annots:

```
let rec filter f l =
  match l with
  | :Nil -> nil
  | (e,l) ->
    if f e is True
    then (e, filter f l)
    else filter f l
  end
```

Well after 3 hours of single-core busy-ness, I killed the process. Now I'm wondering: is this something "dynlang" can't handle and should reject, or would it eventually terminate after (3..n..billions) hours, or might I have triggered a so-far undetected infinite-loop bug? Probably unlikely, but anyway maybe this is of interest to you here  =)

**Comment by E-Sh4rk** [comment]
Hi Phil,
thank you for testing this prototype and for your report :)

> is this something "dynlang" can't handle and should reject, or would it eventually terminate after (3..n..billions) hours

In theory, the type inference always terminates. In practice however, it may take 3 billions hours :) This is the case with this example. However, after 3 billions hours, I think it would infer a type successfully.

If we try with this other example (the only difference is the annotation on `l`):
```ocaml
let rec filter f (l:['a*]) =
  match l with
  | :Nil -> nil
  | (e,l) & :List ->
    if f e is True
    then (e, filter f l)
    else filter f l
  end
```
then it infers the type `(('b -> Any) -> [ 'b* ] -> [ 'b* ]) & (('a -> Any \ True) -> [ 'a* ] -> [  ])`, which is less precise that what we obtain by annotating `f` with the type `('a -> Any \ True) & ('b -> Any)` (this is because the type inference does not try to give `f` an overloaded type).

The reason it takes so long is because of a combinatorial explosion. When infering the type for a recursive function, the type system first tries to infer a type for a stub function that is similar to `filter` but with an additional parameter `filter` (that intuitively represents `filter` itself and that will be called by the body):

```ocaml
let filter_stub filter f l =
  match l with
  | :Nil -> nil
  | (e,l) & :List ->
    if f e is True
    then (e, filter f l)
    else filter f l
  end
```
If you try to type this example, you will see that the type inferred is very complex, because the type inference tries to consider all the cases (if `l` is nil, if `l` is a pair, if `l` is either nil or a pair, if `l` is something else, etc., and then for each case it also tries multiple types for `f` and `filter`).

The second step is the one where the combinatorial explosion happens: the type system tries to type the application of the fixpoint combinator with `filter_stub`:
```ocaml
let fixpoint = fun f ->
  let delta = fun x ->
      f ( fun  v -> ( x x v ))
  in delta delta
(* Has type (('a -> 'b) -> ('a -> 'b) & 'c) -> ('a -> 'b) & 'c *)

let filter = fixpoint filter_stub
```
I am not going into the details here, but the idea is that for typing this application, the type system has solve a "tallying" problem (which the equivalent of "unification" but in presence of semantic subtyping). Here, as the type of `filter_stub` is very complex and feature many type variables, this tallying instance is too complex to be solved in a reasonable time (tallying is decidable but the complexity is exponential).

Maybe we may be able to infer a simpler type for `filter_stub` and/or to solve the tallying instance faster by using heuristics, but for this prototype I wanted to avoid using heuristics as much as possible.

I hope I have answered your questions, and thank you again for experimenting with this prototype!
